version: '3.1'
services: # 컨테이너
  #myapp:
   # build:
    #  context: .
     # dockerfile: Dockerfile
   # depends_on:
    #  db:
     #   condition: service_healthy
    #ports:
    #  - "8080:8080"

  db:
    image: postgres:15
    restart: always
    container_name: postgresql-fifo
    #volumes:
     # - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL",  "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10

  redis:
    image: redis:6.2.5
    hostname: redis
    container_name: redis-fifo
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
