spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  # 쿼리 수행시 콘솔창에 출력되는 옵션 추가
  jpa:
    hibernate:
      ddl-auto: create # 처음에 create로 작성하시고 이후에는 none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  output:
    ansi:
      enabled: always # 콘솔창 색상 적용

  data:
    redis:
      host: localhost
      port: 6379

server.port: 8080

symmetric:
  key: Zmlmby1zcHJpbmdib290LWhhbmdoYWVwcm9qZWN0LXNlY3JldGtleS1qc2tpbS05NDEwMTItOTQxMTE0LW5hdmFsYXJjaHRlY3R1cmUtY2hhaW5zbW9rZXItY29sZHBsYXkK


# 로그 설정
#logging:
 # level:
 #   com.worldticket: info
 # file:
  #  name: log

#smtp:
#  key: ${SMTP_KEY}

#path:
#  firebase_admin_key: ${FB_KEY_PATH}
